-- MySQL Script generated by MySQL Workbench
-- Sun 09 Apr 2017 04:55:19 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_mail_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_mail_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_mail_service` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_mail_service` ;

-- -----------------------------------------------------
-- Table `ulbora_mail_service`.`mail_server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_mail_service`.`mail_server` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `mail_server` VARCHAR(150) NOT NULL,
  `secure_connection` TINYINT(1) NOT NULL,
  `port` INT NOT NULL,
  `debug` TINYINT(1) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_mail_service`.`test_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_mail_service`.`test_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `to_email` VARCHAR(150) NOT NULL,
  `from_email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
